# Generated by Django 5.2 on 2025-04-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='diagnosis_reports/'),
        ),
    ]
